### ISSUE TITLE
[multi-device] TODO

### ISSUE THREAD

**Issue by sachaaaaa** [session-foundation/session-desktop#1152]
- [ ] Friend requests between a paired device and a third-party pubkey are not propagated to the other paired devices
- [ ] Refresh device mappings for active conversations periodically
- [ ] Extract function to get all device mappings (secondary mappings are used to get the primary device pubkey, then get the latter's mapping)
